//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spartak_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersSet
    {
        public int Id { get; set; }
        public int IdNameMaterial { get; set; }
        public int IdClient { get; set; }
        public int IdStaff { get; set; }
        public string Date { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual MaterialsSet MaterialsSet { get; set; }
        public virtual StaffSet StaffSet { get; set; }
    }
}
